import type { FieldConfig, TemplateMeta, TemplateFields } from "@/types/template";

// Shared field definitions — all templates use the same fields
export const EDITOR_FIELDS: FieldConfig[] = [
  {
    key: "title",
    label: "Title",
    type: "text",
    placeholder: "Your headline here",
    required: true,
    group: "content",
  },
  {
    key: "subtitle",
    label: "Subtitle",
    type: "text",
    placeholder: "A brief tagline or description",
    group: "content",
  },
  {
    key: "brandName",
    label: "Brand / Site Name",
    type: "text",
    placeholder: "Acme Inc.",
    group: "content",
  },
  {
    key: "logoUrl",
    label: "Logo",
    type: "file",
    group: "branding",
  },
  {
    key: "accentColor",
    label: "Accent Color",
    type: "color",
    group: "branding",
  },
];

// Template registry
export const TEMPLATES: TemplateMeta[] = [
  {
    id: "minimal",
    name: "Minimal",
    description: "Clean, centered, whitespace-forward",
    tags: ["minimal", "professional"],
    thumbnailGradient: "#ffffff",
    defaults: {
      accentColor: "#6366f1",
      backgroundType: "solid",
      backgroundColor: "#ffffff",
      gradientPreset: "sunset",
    },
  },
  {
    id: "bold",
    name: "Bold",
    description: "Vibrant gradient, large text",
    tags: ["bold", "colorful"],
    thumbnailGradient: "linear-gradient(135deg, #667eea 0%, #764ba2 100%)",
    defaults: {
      accentColor: "#ffffff",
      backgroundType: "gradient",
      backgroundColor: "#667eea",
      gradientPreset: "sunset",
    },
  },
  {
    id: "split",
    name: "Split",
    description: "Asymmetric two-tone, editorial",
    tags: ["professional", "minimal"],
    thumbnailGradient: "linear-gradient(90deg, #ffffff 58%, #2563eb 58%)",
    defaults: {
      accentColor: "#2563eb",
      backgroundType: "solid",
      backgroundColor: "#ffffff",
      gradientPreset: "ocean",
    },
  },
  {
    id: "elegant",
    name: "Elegant",
    description: "Dark background, refined luxury",
    tags: ["dark", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #0a0a0b 0%, #1a1a2e 100%)",
    defaults: {
      accentColor: "#c9a96e",
      backgroundType: "solid",
      backgroundColor: "#0a0a0b",
      gradientPreset: "midnight",
    },
  },
  {
    id: "geometric",
    name: "Geometric",
    description: "Abstract shapes, modern tech",
    tags: ["bold", "colorful", "professional"],
    thumbnailGradient: "#f8fafc",
    defaults: {
      accentColor: "#8b5cf6",
      backgroundType: "solid",
      backgroundColor: "#f8fafc",
      gradientPreset: "sunset",
    },
  },
  {
    id: "frame",
    name: "Frame",
    description: "Decorative border, poster feel",
    tags: ["bold", "dark", "colorful"],
    thumbnailGradient: "linear-gradient(135deg, #1e1b4b 0%, #4338ca 100%)",
    defaults: {
      accentColor: "#e2e8f0",
      backgroundType: "gradient",
      backgroundColor: "#1e1b4b",
      gradientPreset: "indigo",
    },
  },
  {
    id: "layers",
    name: "Layers",
    description: "Overlapping cards, depth and dimension",
    tags: ["colorful", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #cbd5e1 100%)",
    defaults: {
      accentColor: "#0ea5e9",
      backgroundType: "solid",
      backgroundColor: "#f8fafc",
      gradientPreset: "ocean",
    },
  },
  {
    id: "mono",
    name: "Mono",
    description: "Single accent color dominates",
    tags: ["bold", "colorful"],
    thumbnailGradient: "#dc2626",
    defaults: {
      accentColor: "#dc2626",
      backgroundType: "solid",
      backgroundColor: "#dc2626",
      gradientPreset: "ember",
    },
  },
  {
    id: "editorial",
    name: "Editorial",
    description: "Magazine-style layout with elegant typography",
    tags: ["professional", "minimal"],
    thumbnailGradient: "#F4F0EA",
    defaults: {
      accentColor: "#8b4513",
      backgroundType: "solid",
      backgroundColor: "#F4F0EA",
      gradientPreset: "sunset",
    },
  },
  {
    id: "aurora",
    name: "Aurora",
    description: "Organic flowing shapes with glassmorphism",
    tags: ["dark", "colorful"],
    thumbnailGradient: "linear-gradient(135deg, #1a1a2e 0%, #16213e 100%)",
    defaults: {
      accentColor: "#7c3aed",
      backgroundType: "solid",
      backgroundColor: "#0a0a0f",
      gradientPreset: "midnight",
    },
  },
  {
    id: "spotlight",
    name: "Spotlight",
    description: "Dramatic lighting with cinematic feel",
    tags: ["dark", "professional"],
    thumbnailGradient: "#050505",
    defaults: {
      accentColor: "#f59e0b",
      backgroundType: "solid",
      backgroundColor: "#050505",
      gradientPreset: "midnight",
    },
  },
  {
    id: "typographic",
    name: "Typographic",
    description: "Bold typography as art, Swiss poster style",
    tags: ["bold", "minimal", "professional"],
    thumbnailGradient: "#ffffff",
    defaults: {
      accentColor: "#ec4899",
      backgroundType: "solid",
      backgroundColor: "#ffffff",
      gradientPreset: "sunset",
    },
  },
  {
    id: "nebula",
    name: "Nebula",
    description: "Cosmic ethereal with floating particles and starfield",
    tags: ["dark", "colorful", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #080811 0%, #1a1a2e 50%, #2d1b4e 100%)",
    defaults: {
      accentColor: "#8b5cf6",
      backgroundType: "solid",
      backgroundColor: "#080811",
      gradientPreset: "midnight",
    },
  },
  {
    id: "blueprint",
    name: "Blueprint",
    description: "Technical engineering aesthetic with grid and measurements",
    tags: ["professional", "minimal", "bold"],
    thumbnailGradient: "#1a365d",
    defaults: {
      accentColor: "#3b82f6",
      backgroundType: "solid",
      backgroundColor: "#1a365d",
      gradientPreset: "ocean",
    },
  },
  {
    id: "horizon",
    name: "Horizon",
    description: "Sunrise landscape with warm gradients and water reflections",
    tags: ["colorful", "professional"],
    thumbnailGradient: "linear-gradient(180deg, #fef3c7 0%, #fbbf24 50%, #f59e0b 100%)",
    defaults: {
      accentColor: "#f59e0b",
      backgroundType: "solid",
      backgroundColor: "#fef3c7",
      gradientPreset: "amber",
    },
  },
  {
    id: "kinetic",
    name: "Kinetic",
    description: "Dynamic diagonal energy with motion and speed lines",
    tags: ["bold", "colorful", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #fafafa 0%, #e2e8f0 100%)",
    defaults: {
      accentColor: "#ec4899",
      backgroundType: "solid",
      backgroundColor: "#fafafa",
      gradientPreset: "sunset",
    },
  },
  {
    id: "prism",
    name: "Prism",
    description: "Light refraction with glass morphism and rainbow edges",
    tags: ["colorful", "professional", "minimal"],
    thumbnailGradient: "linear-gradient(135deg, #f8fafc 0%, #e2e8f0 50%, #f1f5f9 100%)",
    defaults: {
      accentColor: "#6366f1",
      backgroundType: "solid",
      backgroundColor: "#f8fafc",
      gradientPreset: "indigo",
    },
  },
  {
    id: "noir",
    name: "Noir",
    description: "Cinematic black and white with film grain and vignette",
    tags: ["dark", "professional", "minimal"],
    thumbnailGradient: "linear-gradient(135deg, #0a0a0a 0%, #1a1a1a 100%)",
    defaults: {
      accentColor: "#f59e0b",
      backgroundType: "solid",
      backgroundColor: "#0a0a0a",
      gradientPreset: "midnight",
    },
  },
  {
    id: "glitch",
    name: "Glitch",
    description: "Cyberpunk digital distortion with RGB split and scanlines",
    tags: ["dark", "bold", "colorful"],
    thumbnailGradient: "linear-gradient(135deg, #0a0a0f 0%, #1a1a2e 50%, #0f0f1a 100%)",
    defaults: {
      accentColor: "#00ff9f",
      backgroundType: "solid",
      backgroundColor: "#0a0a0f",
      gradientPreset: "midnight",
    },
  },
  {
    id: "retro",
    name: "Retro",
    description: "80s vaporwave with sunset gradients and neon geometric shapes",
    tags: ["colorful", "bold", "professional"],
    thumbnailGradient: "linear-gradient(180deg, #1a0a2e 0%, #2d1b4e 30%, #ff6b6b 70%, #ffd93d 100%)",
    defaults: {
      accentColor: "#ff6b6b",
      backgroundType: "solid",
      backgroundColor: "#1a0a2e",
      gradientPreset: "ember",
    },
  },
  {
    id: "paper",
    name: "Paper",
    description: "Torn paper collage with layered textures and washi tape accents",
    tags: ["minimal", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #f5f0e8 0%, #e8e0d5 50%, #faf8f5 100%)",
    defaults: {
      accentColor: "#8b7355",
      backgroundType: "solid",
      backgroundColor: "#f5f0e8",
      gradientPreset: "amber",
    },
  },
  {
    id: "fluid",
    name: "Fluid",
    description: "Organic morphing blobs with glassmorphism and depth",
    tags: ["dark", "colorful", "professional"],
    thumbnailGradient: "linear-gradient(135deg, #0f172a 0%, #1e293b 50%, #334155 100%)",
    defaults: {
      accentColor: "#7c3aed",
      backgroundType: "solid",
      backgroundColor: "#0f172a",
      gradientPreset: "midnight",
    },
  },
  {
    id: "code",
    name: "Code",
    description: "Terminal aesthetic with VS Code-inspired dark theme",
    tags: ["dark", "professional", "minimal"],
    thumbnailGradient: "#0d1117",
    defaults: {
      accentColor: "#58a6ff",
      backgroundType: "solid",
      backgroundColor: "#0d1117",
      gradientPreset: "midnight",
    },
  },
  {
    id: "mosaic",
    name: "Mosaic",
    description: "Geometric tile patterns with modern grid layout",
    tags: ["minimal", "professional", "colorful"],
    thumbnailGradient: "linear-gradient(135deg, #fafafa 0%, #f5f5f5 50%, #e5e5e5 100%)",
    defaults: {
      accentColor: "#6366f1",
      backgroundType: "solid",
      backgroundColor: "#fafafa",
      gradientPreset: "indigo",
    },
  },
];

export function getTemplate(id: string): TemplateMeta {
  return TEMPLATES.find((t) => t.id === id) ?? TEMPLATES[0];
}

export const DEFAULT_FIELDS: TemplateFields = {
  title: "",
  subtitle: "",
  brandName: "",
  logoUrl: null,
  accentColor: "#6366f1",
  backgroundType: "solid",
  backgroundColor: "#ffffff",
  gradientPreset: "sunset",
  backgroundImageUrl: null,
};
